# Style & Quality Overrides
AllCops:
  Exclude:
    - 'bin/**/*'

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true

Style/Copyright:
  Enabled: true
  Notice: 'Copyright (\(C\) )?2015 Twitter, Inc.'
  AutocorrectNotice: "# Copyright (C) 2015 Twitter, Inc.\n"
  Exclude:
    - Gemfile

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false
