# Style & Quality Overrides
AllCops:
  TargetRubyVersion: 2.0
  Exclude:
    - 'bin/**/*'

Lint/AssignmentInCondition:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 15

Metrics/PerceivedComplexity:
  Max: 20

Metrics/ParameterLists:
  Max: 10
  CountKeywordArgs: true

Performance/Casecmp:
  Enabled: false

Style/MixinGrouping:
  Enabled: false

Style/MultilineMethodCallBraceLayout:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: always

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: single_quotes
  SupportedStyles:
    - single_quotes
    - double_quotes

Style/NumericLiterals:
  Enabled: false

Style/Copyright:
  Enabled: true
  Notice: 'Copyright (\(C\) )?2015 Twitter, Inc.'
  AutocorrectNotice: "# Copyright (C) 2015 Twitter, Inc.\n"
  Exclude:
    - Gemfile

Style/RaiseArgs:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/DoubleNegation:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/SignalException:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/FormatString:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TernaryParentheses:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/VariableNumber:
  Enabled: false

Style/MultilineIfModifier:
  Enabled: false

Style/IdenticalConditionalBranches:
  Enabled: false

Style/EmptyLineAfterMagicComment:
  Enabled: false

Metrics/BlockLength:
  Enabled: false